Fact 2080
puppetlabs/facter-ng pull request #109
Opened 2019-10-22 13:08 UTC by gigicampean

2019-10-24 11:28 UTC, sebastian-miclea commented on lib/resolvers/memory_resolver.rb
> +            output.each_line do |line|
Instead of iterating through the entire list, you could catch the result directly.
`output.match(/MemTotal:\s+(\d+)\s/)[1]`

2019-10-24 11:28 UTC, sebastian-miclea commented on lib/resolvers/memory_resolver.rb
> +            @fact_list[:capacity] = ((@fact_list[:used_bytes] / @fact_list[:total]) * (100 / 100))
Why are we multiplying by 1?

2019-10-24 11:36 UTC, BogdanIrimie requested changes

2019-10-24 11:36 UTC, IrimieBogdan commented on lib/resolvers/memory_resolver.rb
> +            output, _status = Open3.capture2('cat /proc/meminfo')
`File.read(file_name)` should be used instead of `Open3.capture2` with `cat`

2019-10-24 11:36 UTC, IrimieBogdan commented on lib/resolvers/memory_resolver.rb
> +            @fact_list[:capacity] = ((@fact_list[:used_bytes] / @fact_list[:total]) * (100 / 100))
From the old facter
```
memory => {
  swap => {
    available => "1.19 GiB",
    available_bytes => 1279258624,
    capacity => "0%",
    total => "1.19 GiB",
    total_bytes => 1279258624,
    used => "0 bytes",
    used_bytes => 0
  },
  system => {
    available => "3.65 GiB",
    available_bytes => 3917336576,
    capacity => "5.24%",
    total => "3.85 GiB",
    total_bytes => 4133920768,
    used => "206.55 MiB",
    used_bytes => 216584192
  }
}
```
this value is a percent (%). The formula should be changed to `@fact_list[:used_bytes]  * @fact_list[:total] / 100`

2019-10-24 11:36 UTC, IrimieBogdan commented on lib/resolvers/memory_resolver.rb
> +            @fact_list[:scapacity] = ((@fact_list[:sused_bytes] / @fact_list[:swap_total]) * (100 / 100))
Same as for capacity.

2019-10-24 11:36 UTC, IrimieBogdan commented on lib/resolvers/memory_resolver.rb
> +            output.each_line do |line|
I would break this this method and create 2 new methods (read system and read swap).

2019-10-25 11:10 UTC, sebastian-miclea commented on spec/facter/resolvers/memory_resolver_spec.rb
> +describe 'MemoryResolver' do
Please add tests for all the keys that are returned by the resolver, especially the ones that have calculations.

2019-10-28 10:07 UTC, sebastian-miclea commented on spec/facter/resolvers/memory_resolver_spec.rb
> +    expect(result).to eq(4_036_680 * 1024)
You could also use the vars defined with let for these tests.

2019-10-28 11:22 UTC, BogdanIrimie approved these changes

2019-10-28 11:37 UTC, sebastian-miclea approved these changes

2019-10-28 11:38 UTC, merged