(FACT-2099) Created dmi resolver for fedora.
puppetlabs/facter-ng pull request #136
Opened 2019-11-01 14:59 UTC by gigicampean

Tests coming in the next commit.

2019-11-04 15:09 UTC, oanatmaria commented on lib/resolvers/dmi_resolver.rb
> +          # Version
i think these comments are lying

2019-11-04 15:09 UTC, oanatmaria commented on lib/resolvers/dmi_resolver.rb
> +              @fact_list[element.to_sym] = File.read("/sys/class/dmi/id/#{element}")
chassis type should be translated as it is in c facter (see @ [https://github.com/puppetlabs/facter/blob/2fb90639661e03837507bec7ee38f6d68322b19f/lib/src/facts/resolvers/dmi_resolver.cc#L39](url) )

2019-11-04 15:09 UTC, oanatmaria commented on spec/facter/resolvers/dmi_resolver_spec.rb
> +    allow(File).to receive(:read).with('/sys/class/dmi/id/product_uuid').and_return(product_uuid)
i think it would look better if these files will be in separated contexts like: [https://confluence.puppetlabs.com/pages/viewpage.action?spaceKey=FACTERNG&title=Write+rspec+tests](url)

2019-11-05 09:31 UTC, gigicampean commented on lib/resolvers/dmi_resolver.rb
> +              @fact_list[element.to_sym] = File.read("/sys/class/dmi/id/#{element}")
404

2019-11-06 13:14 UTC, sebastian-miclea commented on lib/resolvers/dmi_resolver.rb
>              files.each do |element|
Try to be constant with var names. You have a list of files, but individually they are elements.

2019-11-07 15:08 UTC, BogdanIrimie requested changes

2019-11-07 15:08 UTC, IrimieBogdan commented on lib/resolvers/dmi_resolver.rb
> +          # :product_uuid
Some of the comments should be updated, because they cannot be resolved by this resolver.

2019-11-07 15:08 UTC, IrimieBogdan commented on lib/resolvers/dmi_resolver.rb
> +            end
We should read a file only when the fact that resides in that file is requested from the resolver.

2019-11-12 09:52 UTC, BogdanIrimie approved these changes

2019-11-12 09:59 UTC, merged