(FACT-2200) Implemented dmi fact for OSX.
puppetlabs/facter-ng pull request #189
Opened 2019-12-16 12:20 UTC by gigicampean

2019-12-16 16:16 UTC, BogdanIrimie requested changes
None of the facts work. The DMI resolver only works for Linux.

2019-12-19 09:59 UTC, BogdanIrimie requested changes

2019-12-19 09:59 UTC, IrimieBogdan commented on lib/framework/core/file_loader.rb
> +load_lib_dirs('resolvers', os.to_s, '**') if os.to_s =~ /win|aix|solaris|macosx/
In order to fix the merge conflict, you should take the version that is on master for file_loader

2019-12-19 12:23 UTC, gigicampean commented on lib/framework/core/file_loader.rb
> +load_lib_dirs('resolvers', os.to_s, '**') if os.to_s =~ /win|aix|solaris|macosx/
The conflict was resolved ! :)

2019-12-20 12:52 UTC, BogdanIrimie approved these changes

2019-12-20 12:52 UTC, merged