(FACT-2237) ssh fact for AIX
puppetlabs/facter-ng pull request #206
Opened 2019-12-17 13:44 UTC by GeorgeMrejea

2019-12-18 12:08 UTC, gimmyxd commented on lib/facts/aix/ssh.rb
> +        result.each { |ssh| ssh_facts.merge!(create_ssh_fact(ssh)) }
You can do this in a single line using `map` instead of each 
You can define it as a new private method, `ssh_facts` and just call it when you create the resolved fact

```ruby
result.map! { |el| create_ssh_fact(el)}.first
```

2019-12-19 13:54 UTC, oanatmaria commented on spec/facter/facts/aix/ssh_spec.rb
> +      expect(fact.call_the_resolver).to eq(expected_fact)
could you please add another test where there are more ssh elements in result?

2019-12-20 10:20 UTC, gimmyxd commented on lib/facts/aix/ssh.rb
> +      end
I would suggest a refactoring for this as, though this would apply for all the existing.
```ruby
# frozen_string_literal: true

module Facter
  module Aix
    class Ssh
      FACT_NAME = 'ssh'

      def call_the_resolver
        ResolvedFact.new(FACT_NAME, fact_value)
      end

      private

      def fact_value
        resolver_data.map! { |el| create_ssh_fact(el) }.inject(:merge!)
      end

      def resolver_data
        Resolvers::SshResolver.resolve(:ssh)
      end

      def create_ssh_fact(ssh)
        {
          ssh.name.to_sym => {
            fingerprints: {
              sha1: ssh.fingerprint.sha1,
              sha256: ssh.fingerprint.sha256
            },
            key: ssh.key,
            type: ssh.type
          }
        }
      end
    end
  end
end
```
cc: @IrimieBogdan @sebastian-miclea

2019-12-20 14:29 UTC, gimmyxd requested changes

2019-12-20 14:29 UTC, gimmyxd commented on spec/facter/facts/aix/ssh_spec.rb
> +      result << ssh2
You don't need to create an empty array and add elements to it
```ruby
ssh1 = Facter::Ssh.new(Facter::FingerPrint.new('test', 'test'), 'ecdsa', 'test', 'ecdsa')
ssh2 = Facter::Ssh.new(Facter::FingerPrint.new('test2', 'test2'), 'rsa', 'test2', 'rsa')
result = [ssh1, ssh2]
```

2019-12-20 14:29 UTC, gimmyxd commented
@GeorgeMrejea please squash the commits

2019-12-20 15:13 UTC, gimmyxd approved these changes

2019-12-23 09:05 UTC, merged