(FACT-2203) Identity fact for OSX
puppetlabs/facter-ng pull request #215
Opened 2019-12-18 13:01 UTC by Dorin-Pleava

This commit adds the identity fact to osx platforms

2019-12-18 14:29 UTC, oanatmaria commented on lib/resolvers/identity_resolver.rb
> +        def retrieve_identity(fact_name)
make this method private

2019-12-19 10:15 UTC, GeorgeMrejea requested changes

2019-12-19 10:15 UTC, GeorgeMrejea commented on lib/resolvers/identity_resolver.rb
> +          passwd = Etc.getpwuid
I would like a better name, this objects contains more than password. Suggest `login_info`

2019-12-19 13:16 UTC, oanatmaria commented on lib/resolvers/identity_resolver.rb
> +          @fact_list[fact_name]
could you add some unit tests for this resolver?

2019-12-19 14:11 UTC, Dorin-Pleava commented on lib/resolvers/identity_resolver.rb
> +          passwd = Etc.getpwuid
Agreed. I used passwd as that is the name of the structure returned. https://docs.ruby-lang.org/en/2.0.0/Etc.html#method-c-getpwuid. Will change

2019-12-20 09:04 UTC, GeorgeMrejea commented on lib/resolvers/identity_resolver.rb
> +          @fact_list[:privileged] = passwd.uid.zero?.to_s
privileged is boolean, remove to_s

2019-12-24 11:06 UTC, Dorin-Pleava commented on lib/resolvers/identity_resolver.rb
> +          @fact_list[:privileged] = passwd.uid.zero?.to_s
Removing to_s will cause identity.privileged to not show up when executing `facter-ng identity.privileged`. It can be made to a boolean, but it will have to be converted in the fact to string.

2019-12-24 13:00 UTC, GeorgeMrejea commented on lib/resolvers/identity_resolver.rb
> +          @fact_list[:privileged] = passwd.uid.zero?.to_s
```
[0] [AIX] root@aix71-9:~ # /root/facter-ng/bin/facter-ng identity.privileged
true
[0] [AIX] root@aix71-9:~ # date
Tue Dec 24 05:00:13 PST 2019
[0] [AIX] root@aix71-9:~ #
```

2019-12-24 13:01 UTC, GeorgeMrejea commented on lib/resolvers/identity_resolver.rb
> +          @fact_list[:privileged] = passwd.uid.zero?.to_s
```
[0] [AIX] root@aix71-9:~ # /root/facter-ng/bin/facter-ng identity
{
  gid => 0,
  group => "system",
  privileged => true,
  uid => 0,
  user => "root"
}
```

2020-01-06 12:35 UTC, Dorin-Pleava commented on lib/resolvers/identity_resolver.rb
> +          @fact_list[:privileged] = passwd.uid.zero?.to_s
I get the same result on a privileged system, but when identity.privileged returns false, nothing is displayed. That is why I convert it to string.
Can you try `facter-ng identity.privileged` on a system where it should return boolean false?

2020-01-06 15:18 UTC, IrimieBogdan commented on lib/resolvers/identity_resolver.rb
> +          @fact_list[:privileged] = passwd.uid.zero?.to_s
Was fixed by a change in legacy formatter.

2020-01-07 11:50 UTC, BogdanIrimie submitted a review, later dismissed

2020-01-07 11:50 UTC, gimmyxd submitted a review, later dismissed

2020-01-07 11:50 UTC, gimmyxd commented on lib/framework/formatters/legacy_fact_formatter.rb
> +      resolved_facts.select { |fact| fact.value.nil? }.map { |fact| fact.value = '' }
You can do this in a single iteration: `resolved_facts.map { |fact| fact.nil? ? "" : fact }`
Do we want to return o copy of the facts or it is ok to update the values inplace?

2020-01-07 11:54 UTC, GeorgeMrejea submitted a review, later dismissed

2020-01-07 12:10 UTC, gimmyxd commented on spec/facter/resolvers/identity_resolver_spec.rb
> +  end
nit: you can dry this a bit with shared_examples: https://relishapp.com/rspec/rspec-core/v/3-8/docs/example-groups/shared-examples

```ruby
shared_examples_for "a resolved fact" do |fact_name, value|
    subject { Facter::Resolvers::PosxIdentity.resolve(fact_name) }
    it { is_expected.to eql(value) }
  end

  describe 'GID' do
    it_behaves_like 'a resolved fact', :gid, 20
  end

  describe 'GROUP' do
    it_behaves_like 'a resolved fact', :group, 'staff'
  end
  ...
```

2020-01-07 13:56 UTC, Dorin-Pleava commented on lib/framework/formatters/legacy_fact_formatter.rb
> +      resolved_facts.select { |fact| fact.value.nil? }.map { |fact| fact.value = '' }
We want just the value of the fact to be `''`, not the whole fact object. Filtering first with select, and then changing the value seems to be easier.
Also I think it's OK to modify in place.

2020-01-07 14:35 UTC, BogdanIrimie approved these changes

2020-01-07 14:35 UTC, merged