(FACT-2176) Return structured data on executable facts
puppetlabs/facter-ng pull request #328
Opened 2020-03-02 13:28 UTC by florindragos

2020-03-03 12:40 UTC, Filipovici-Andrei requested changes

2020-03-03 12:40 UTC, Filipovici-Andrei commented on lib/custom_facts/util/parser.rb
> +          parse_executable_output output
The parameters need to be within parentheses.

2020-03-03 12:40 UTC, Filipovici-Andrei commented on lib/custom_facts/util/parser.rb
> +          parse_executable_output LegacyFacter::Core::Execution.exec(quote(filename))
The parameters need to be within parentheses.

2020-03-04 11:29 UTC, oanatmaria commented on lib/custom_facts/util/parser.rb
> +        end
Could you please add a test for these changes?

2020-03-05 10:46 UTC, florindragos commented on lib/custom_facts/util/parser.rb
> +        end
done

2020-03-05 10:50 UTC, oanatmaria approved these changes

2020-03-05 10:55 UTC, Filipovici-Andrei approved these changes

2020-03-05 10:55 UTC, merged