(FACT-2419) Module structure that respects rubocop
puppetlabs/facter-ng pull request #329
Opened 2020-03-02 14:34 UTC by oanatmaria

2020-03-03 12:36 UTC, Filipovici-Andrei requested changes

2020-03-03 12:36 UTC, Filipovici-Andrei commented on spec/custom_facts/util/confine_spec.rb
> +    it "returns true if any of the provided symbol values matches the fact's value as a sctring" do
probably string instead of sctring?

2020-03-03 13:20 UTC, oanatmaria commented on lib/facts/aix/ssh.rb
> +        Facter::Resolvers::SshResolver.resolve(:ssh)
Resolvers are not in the scope of this PR and they will be tracked under another ticket

2020-03-03 13:22 UTC, oanatmaria commented on lib/facts/macosx/network_ip.rb
> +    class NetworkIp
this file should and will be deleted

2020-03-03 13:23 UTC, oanatmaria commented on lib/facts/macosx/ruby/sitedir.rb
> +      class Sitedir
the file is sitedir, in order to be with a capital D the file name should have been site_dir

2020-03-03 15:04 UTC, oanatmaria commented
Everything passed on puppet-agent https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/763/. Also facter's acceptance tests.

2020-03-04 09:19 UTC, Filipovici-Andrei approved these changes

2020-03-04 09:20 UTC, merged

2020-03-05 08:25 UTC, gimmyxd commented on .rubocop_todo.yml
>      - 'spec/facter/facts/solaris/zpool_featureversions_spec.rb'
This should also be fixd:
```❯ cat spec/facter/facts/solaris/zpool_featureversions_spec.rb
# frozen_string_literal: true

describe Facts::Solaris::ZpoolFeaturenumbers do
  describe '#call_the_resolver' do
    subject(:fact) { Facts::Solaris:
....
```

2020-03-05 08:25 UTC, gimmyxd commented on .rubocop_todo.yml
>      - 'spec/facter/facts/macosx/load_average_spec.rb'
the files should be called: `load_averages_spec.rb`