(FACT-2447) Add macosx legacy facts
puppetlabs/facter-ng pull request #353
Opened 2020-03-10 12:31 UTC by florindragos

2020-03-11 10:40 UTC, sebastian-miclea commented on lib/facts/macosx/memory/system/available_bytes.rb
> +             Facter::ResolvedFact.new(ALIASES, fact_value ? (fact_value / (1024.0 * 1024.0)).round(2) : nil, :legacy)]
Could you please move the logic outside the method call? 
Maybe it's worth to add an util method.

2020-03-12 08:48 UTC, Filipovici-Andrei commented on lib/facts/macosx/memory/system/available_bytes.rb
> +             Facter::ResolvedFact.new(ALIASES, fact_value ? (fact_value / (1024.0 * 1024.0)).round(2) : nil, :legacy)]
This will be implemented with ticket [FACT-2459](https://tickets.puppetlabs.com/browse/FACT-2459)

2020-03-12 09:07 UTC, Filipovici-Andrei requested changes

2020-03-12 09:07 UTC, Filipovici-Andrei commented on spec/facter/facts/macosx/system_uptime/uptime_spec.rb
>      it 'returns a resolved fact' do
The test description should contain what fact is being returned, not just a resolved one

2020-03-13 13:34 UTC, oanatmaria commented on lib/facts/macosx/processors/models.rb
> +          puts facts.inspect
remove this line

2020-03-13 13:37 UTC, oanatmaria commented on lib/facts/macosx/system_profiler/uptime.rb
> +        ALIASES = 'uptime'
sp_uptime

2020-03-13 13:47 UTC, oanatmaria commented on spec/facter/facts/macosx/memory/swap/total_bytes_spec.rb
>  describe Facts::Macosx::Memory::Swap::TotalBytes do
Could you please run `rubocop --auto-gen-config --exclude-limit 1000` and update .rubocop_todo file?

2020-03-13 13:48 UTC, oanatmaria submitted a review, later dismissed

2020-03-13 14:12 UTC, Filipovici-Andrei approved these changes

2020-03-13 14:14 UTC, merged