(FACT-2449) Added Solaris legacy facts
puppetlabs/facter-ng pull request #362
Opened 2020-03-11 12:09 UTC by sebastian-miclea

2020-03-12 15:20 UTC, Filipovici-Andrei requested changes

2020-03-12 15:20 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/solaris_zones/zone_spec.rb
> +      puts fact.call_the_resolver.inspect
this puts is not needed

2020-03-12 15:20 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/os/hardware_spec.rb
> +      # expect(Facter::Resolvers::Uname).to have_received(:resolve).with(:machine)
remove commented code

2020-03-12 15:20 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/os/hardware_spec.rb
> +      allow(Facter::Resolvers::Uname).to receive(:resolve)
I don't think this mock is necessary because you have it defined in the before block

2020-03-12 15:20 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/ruby/platform_spec.rb
> -      expect(fact.call_the_resolver)
switch line 14 with 15 and change receive to have_received

2020-03-12 15:20 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/ruby/sitedir_spec.rb
> -      expect(fact.call_the_resolver)
switch line 14 with 15 and change receive to have_received

2020-03-12 15:20 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/solaris_zones/current_spec.rb
>        fact = Facts::Solaris::SolarisZones::Current.new
To follow the current testing strategy I think this should be the subject.

2020-03-12 15:20 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/solaris_zones/current_spec.rb
>        allow(Facter::Resolvers::SolarisZoneName).to receive(:resolve).with(:current_zone_name).and_return('global')
this can be moved inside a before block, so we can keep the test focused on what we test, not how we set up the environment

2020-03-12 15:20 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/solaris_zones/zone_spec.rb
>        fact = Facts::Solaris::SolarisZones::Zone.new
this should be the test's subject

2020-03-12 15:20 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/solaris_zones/zone_spec.rb
> +      expected_fact_uuid = Facter::ResolvedFact.new('zone_global_uuid', result[:uuid])
I think that all the environment preparation should go into a before block

2020-03-16 10:12 UTC, Filipovici-Andrei requested changes

2020-03-16 10:12 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/solaris_zones/zone_spec.rb
> +    allow(Facter::ResolvedFact).to receive(:new)
I'm not sure you need this mock. If you plan to use it, maybe the expected facts should contain assertions for the ResolvedFact mock.

2020-03-16 10:42 UTC, Filipovici-Andrei requested changes

2020-03-16 10:42 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/solaris_zones/current_spec.rb
> +    allow(Facter::ResolvedFact).to receive(:new)
You have mocked the ResolvedFacts and made them return themselves. Don't you think it would be better to not mock them at all, and just check in the test ResolvedFact got called with what we wanted. Also it would keep the consistency of how we write tests.

2020-03-16 12:17 UTC, sebastian-miclea commented on spec/facter/facts/solaris/solaris_zones/zone_spec.rb
> +    allow(Facter::ResolvedFact).to receive(:new)
I need this line, I used one line to mock every new ResolvedFact created instead of mocking using doubles. The result of the doubled ResolvedFacts are tested in line 42

2020-03-16 12:40 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/solaris_zones/zone_spec.rb
> +    allow(Facter::ResolvedFact).to receive(:new)
Yes, I understand it now.

2020-03-16 15:32 UTC, Filipovici-Andrei approved these changes

2020-03-16 15:33 UTC, merged