(maint) Add yard documentation
puppetlabs/facter-ng pull request #365
Opened 2020-03-12 09:17 UTC by sebastian-miclea

2020-03-12 15:48 UTC, Filipovici-Andrei requested changes

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    # Check whether debuging is inabled
enabled is spelled incorrectly

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    # @return [Array<String>] An array of the directories searched
An array of searched directories, sounds better

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    # @return [Array<String>] An array of the directories searched
Same as the above comment

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    # Check whether printing stack trace is inabled
enabled spelled incorrectly

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    # @param debug_bool [bool] State which trace should have
Set trace state, or Set trace on debug state, probably sounds better

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    # @return [String the value of the fact, or nil if no fact is found
missing ']' after String. The fact value, or nil if no fact is found, sounds better

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    # @return [Integer, nil] Will return status 1 if ueser query contains
user spelled incorrectly

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    #  facts that are not found and resolved, otherwise it will return nil
Is it 'not found and resolved', or, 'not found or resolved'?

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    # Prints out blocked facts before when to_hash or to_user_output
What you are trying to say is: Also prints blocked facts, when to_hash or to_user_output is called?

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    # Print out error messages to
I think that Print an error message, sounds better

2020-03-12 15:48 UTC, Filipovici-Andrei commented on lib/facter.rb
> +    # Proxy method catch metod calls that were not implemented yet
method not spelled correctly and I think Proxy method that catches not yet implemented method calls, sounds a little better

2020-03-16 08:25 UTC, sebastian-miclea commented on lib/facter.rb
> +    #  facts that are not found and resolved, otherwise it will return nil
it should be not found or resolved

2020-03-16 09:54 UTC, IrimieBogdan commented on lib/facter.rb
> +    # Register directories to be searched for facts. The registered directories
... to be searched for custom facts.

2020-03-16 09:55 UTC, IrimieBogdan commented on lib/facter.rb
> +    # Returns the registered search directories.
... search directories for external facts.

2020-03-16 09:55 UTC, IrimieBogdan commented on lib/facter.rb
> +    # Returns the registered search directories.
... search directories for custom facts.

2020-03-16 09:57 UTC, IrimieBogdan commented on lib/facter.rb
> +    # Gets a hash mapping fact names to their values
The hash contains core facts, legacy facts, custom facts and external facts (all facts that can be resolved).

2020-03-16 09:59 UTC, IrimieBogdan commented on lib/facter.rb
> +    # @api public
This is an internal API and must be private. It contains a string with facts formatted the way user specified from CLI.

2020-03-16 10:09 UTC, IrimieBogdan commented on lib/facter.rb
> +    # I think that Print an error message
It is used for printing errors regarding CLI user input validation

2020-03-16 10:13 UTC, IrimieBogdan commented on lib/facter.rb
> +    # Returns a fact object by name
Resolved facts and saves the result in @already_searched array that is used as a global collection.

2020-03-16 10:13 UTC, sebastian-miclea commented on lib/facter.rb
> +    # @api public
This cannot be called as private, it gets called from outside the module.

2020-03-16 13:04 UTC, BogdanIrimie approved these changes

2020-03-16 15:45 UTC, Filipovici-Andrei approved these changes

2020-03-16 15:45 UTC, merged