(FACT-2474) Add identity facts
puppetlabs/facter-ng pull request #379
Opened 2020-03-16 13:33 UTC by oanatmaria

2020-03-17 09:47 UTC, florindragos commented on lib/facts/aix/identity/group.rb
> +          Facter::ResolvedFact.new(FACT_NAME, fact_value)
this is not needed

2020-03-17 12:16 UTC, Filipovici-Andrei requested changes

2020-03-17 12:16 UTC, Filipovici-Andrei commented on spec/facter/facts/solaris/identity/gid_spec.rb
> +    it 'returns a fact' do
you can set the example description to something more meaningful as you have in other tests

2020-03-17 12:16 UTC, Filipovici-Andrei commented on spec/facter/facts/sles/identity/user_spec.rb
> +    it 'returns a fact' do
A better description would be better

2020-03-18 11:13 UTC, florindragos submitted a review, later dismissed

2020-03-18 13:31 UTC, Filipovici-Andrei submitted a review, later dismissed

2020-03-18 13:35 UTC, Filipovici-Andrei approved these changes

2020-03-18 13:38 UTC, merged