(FACT-2471) Add Linux partitions fact
puppetlabs/facter-ng pull request #393
Opened 2020-03-19 16:40 UTC by oanatmaria

2020-03-19 16:42 UTC, oanatmaria commented
Do not merge label is there because I need to write some unit tests for resolver.

2020-03-24 07:33 UTC, Filipovici-Andrei requested changes

2020-03-24 07:33 UTC, Filipovici-Andrei commented on spec/facter/resolvers/partitions_spec.rb
> +      let(:sys_block_subdirs) { ['.', '..', 'sda'] }
this let can be moved at the top of the test, and deleted from the other tests.

2020-03-24 07:33 UTC, Filipovici-Andrei commented on spec/facter/resolvers/partitions_spec.rb
> +    before do
This before block should be deleted because it's being overwritten in the following contexts that contain before blocks with the same allow statements.

2020-03-24 07:33 UTC, Filipovici-Andrei commented on lib/resolvers/partitions.rb
> +          blocks = Dir.entries(BLOCK_PATH).reject { |dir| dir =~ /^\.+/ }
Shouldn't this variable be named block_devices? Block doesn't quite suggest anything.

2020-03-24 07:33 UTC, Filipovici-Andrei commented on lib/resolvers/partitions.rb
> +              device_for_path_exists(block_path)
device_for_path_exists, dm_for_path_exists and loop_for_path_exists don't check that something for path exists, they populate partitions, so I think they should be named, something like, extract_partitions_from_dm...path, ...loop

2020-03-24 07:33 UTC, Filipovici-Andrei commented on spec/facter/resolvers/partitions_spec.rb
> +    context 'when block have a dm subdir' do
it's has instead of have. The same for the other contexts.

2020-03-24 07:33 UTC, Filipovici-Andrei commented on spec/facter/resolvers/partitions_spec.rb
> +      let(:parts) do
what is parts? Could you please give it a more suggestive name?

2020-03-24 14:33 UTC, Filipovici-Andrei approved these changes

2020-03-26 14:59 UTC, BogdanIrimie approved these changes

2020-03-26 14:59 UTC, merged