(FACT-2504) Fix RSpec/MultipleExpectations offences
puppetlabs/facter-ng pull request #419
Opened 2020-03-30 12:09 UTC by oanatmaria

2020-03-31 16:14 UTC, Filipovici-Andrei requested changes

2020-03-31 16:18 UTC, oanatmaria commented on spec/custom_facts/core/resolvable_spec.rb
>        expect(resolvable).not_to receive(:timeout)
RSpec/MessageSpies is another rubocop offence that will be handle under another ticket

2020-03-31 16:18 UTC, oanatmaria commented on spec/custom_facts/util/collection_spec.rb
>          expect do
RSpec/MessageSpies is another rubocop offence that will be handle under another ticket

2020-03-31 16:19 UTC, oanatmaria commented on spec/custom_facts/util/loader_spec.rb
> +      expect(Kernel).to receive(:load).with('/one/dir/testing.rb')
RSpec/MessageSpies is another rubocop offence that will be handle under another ticket

2020-03-31 16:19 UTC, oanatmaria commented on spec/custom_facts/util/loader_spec.rb
>        expect(Kernel).not_to receive(:load)
RSpec/MessageSpies is another rubocop offence that will be handle under another ticket

2020-03-31 16:19 UTC, oanatmaria commented on spec/custom_facts/util/loader_spec.rb
>          expect(Kernel).to receive(:load).with(f)
RSpec/MessageSpies is another rubocop offence that will be handle under another ticket

2020-03-31 16:19 UTC, oanatmaria commented on spec/custom_facts/util/loader_spec.rb
>        expect(Kernel).to receive(:load).with('/two/dir/d.rb')
RSpec/MessageSpies is another rubocop offence that will be handle under another ticket

2020-03-31 16:19 UTC, oanatmaria commented on spec/facter/facter_spec.rb
>          expect_any_instance_of(Facter::Log).not_to receive(:debug).with(message)
RSpec/MessageSpies is another rubocop offence that will be handle under another ticket

2020-03-31 16:19 UTC, oanatmaria commented on spec/custom_facts/util/fact_spec.rb
>        expect(simple).to receive(:flush)
RSpec/MessageSpies is another rubocop offence that will be handle under another ticket

2020-03-31 16:20 UTC, oanatmaria commented on spec/custom_facts/util/loader_spec.rb
>        expect(Kernel).to receive(:load).with('/one/dir/testing.rb')
RSpec/MessageSpies is another rubocop offence that will be handle under another ticket

2020-03-31 17:19 UTC, IrimieBogdan commented on spec/facter/query_parser_spec.rb
> +      expect(matched_facts).to be_an_instance_of(Array).and \
For complex objects I would go with the version in the PR, it is easier to read.

2020-03-31 17:20 UTC, IrimieBogdan commented on spec/custom_facts/core/aggregate_spec.rb
> +      expect(output).to be_an_instance_of(Array).and contain_exactly('foo', 'foo bar')
For strings, the shorter version is succinct and I would go with the approach @Filipovici-Andrei  proposed

2020-04-02 11:53 UTC, Filipovici-Andrei approved these changes

2020-04-02 11:54 UTC, merged