(FACT-2330) Add ssh fact for Windows OpenSSH feature
puppetlabs/facter-ng pull request #424
Opened 2020-03-31 16:06 UTC by oanatmaria

2020-04-08 07:58 UTC, sebastian-miclea commented on lib/resolvers/ssh_resolver.rb
> +              key_name = SshHelper.determine_ssh_key_name(key_type)
Could we do this in the SshHelper? I don't see key_name being used anywhere else besides calling an other method from SshHelper.

2020-04-08 08:05 UTC, sebastian-miclea commented on lib/resolvers/utils/ssh_helper.rb
> +        SSH_NAME[key]
I don't think that a method is needed to access a key from a hash.

2020-04-08 08:15 UTC, gimmyxd commented on lib/framework/core/file_loader.rb
> +require "#{ROOT_DIR}/lib/resolvers/utils/ssh_helper.rb"
Why there is a util/shh and a util/ssh_helper?
This is a bit confusing, alongside the fact that utils are in different locations with different purposes. Could this 2 ssh be a single source?

2020-04-08 08:59 UTC, IrimieBogdan commented on lib/facts/windows/ssh.rb
> +        result = Facter::Resolvers::Windows::Ssh.resolve(:ssh) if privileged
`result` variable should have a suggestive name

2020-04-08 12:27 UTC, oanatmaria commented on lib/resolvers/ssh_resolver.rb
> +              key_name = SshHelper.determine_ssh_key_name(key_type)
Done

2020-04-08 12:27 UTC, oanatmaria commented on lib/resolvers/utils/ssh_helper.rb
> +        SSH_NAME[key]
I removed it

2020-04-08 12:27 UTC, oanatmaria commented on lib/facts/windows/ssh.rb
> +        result = Facter::Resolvers::Windows::Ssh.resolve(:ssh) if privileged
done

2020-04-08 12:51 UTC, oanatmaria commented on lib/framework/core/file_loader.rb
> +require "#{ROOT_DIR}/lib/resolvers/utils/ssh_helper.rb"
util/shh is an object that contains structured information about a ssh key. util/ssh_helper creates an object of type util/shh after creating a fingerprint and extracting other information

2020-04-08 14:51 UTC, Filipovici-Andrei requested changes

2020-04-08 14:51 UTC, Filipovici-Andrei commented on lib/resolvers/utils/ssh_helper.rb
> +  class SshHelper
Shouldn't you also have a module named Utils?

2020-04-08 14:51 UTC, Filipovici-Andrei commented on spec/facter/facts/windows/ssh_spec.rb
> +      end
This two tests can be put into a shared example

2020-04-08 14:51 UTC, Filipovici-Andrei commented on spec/facter/resolvers/windows/ssh_spec.rb
> +        it 'returns nil' do
Probably also a test when just one file is not readable, might be a good test

2020-04-12 15:43 UTC, oanatmaria commented on spec/facter/resolvers/windows/ssh_spec.rb
> +        it 'returns nil' do
in context 'when ecdsa, ed25519 and rsa files exists' do implays that dsa file is not readable

2020-04-12 15:43 UTC, oanatmaria commented on lib/resolvers/utils/ssh_helper.rb
> +  class SshHelper
Done

2020-04-12 15:44 UTC, oanatmaria commented on spec/facter/facts/windows/ssh_spec.rb
> +      end
We decided that a shared example will degenerate over time so we will avoid those

2020-04-13 13:46 UTC, Filipovici-Andrei commented on spec/facter/resolvers/windows/ssh_spec.rb
> +        it 'returns nil' do
Ok

2020-04-13 13:50 UTC, Filipovici-Andrei commented on spec/facter/facts/windows/ssh_spec.rb
> +      end
Anything can degenerate if we do stupid things. And that shouldn't be a reason to completely avoid using a programming paradigm.

2020-04-13 14:14 UTC, Filipovici-Andrei commented on lib/resolvers/utils/ssh_helper.rb
> +  class SshHelper
I think the correct namespace should be Facter::Resolvers::Utils::SshHelper

2020-04-15 08:25 UTC, Filipovici-Andrei requested changes

2020-04-15 08:25 UTC, Filipovici-Andrei commented on lib/resolvers/windows/ssh.rb
> +              next unless File.readable?(File.join(ssh_dir, file_name))
You should use the FileHelper.safe_read

2020-04-15 08:33 UTC, oanatmaria commented on lib/resolvers/windows/ssh.rb
> +              next unless File.readable?(File.join(ssh_dir, file_name))
Done

2020-04-15 08:42 UTC, Filipovici-Andrei approved these changes

2020-04-15 08:46 UTC, merged

2020-04-15 10:16 UTC, gimmyxd commented on lib/facts/windows/ssh.rb
> +      def create_ssh_fact(ssh)
Isn't this duplicated in each ssh fact? is there a ticket to solve the duplications?