(FACT-2538) Don't save facts in collection if they have nill value.
puppetlabs/facter-ng pull request #441
Opened 2020-04-09 14:27 UTC by IrimieBogdan

2020-04-09 14:48 UTC, Filipovici-Andrei requested changes
Nice, at least one unit test would be better😆

2020-04-09 14:59 UTC, IrimieBogdan commented
Added unit tests.

2020-04-09 15:02 UTC, IrimieBogdan commented on lib/models/fact_collection.rb
> +        next if (fact.type == :core || fact.type == :legacy) && fact.value.nil?
Didn't use `fact.type =~ /core|legacy/` because regex are slow

2020-04-09 15:26 UTC, gimmyxd commented on lib/models/fact_collection.rb
> +        next if (fact.type == :core || fact.type == :legacy) && fact.value.nil?
How about `%i[core, legacy].include?(fact.type)` ?

2020-04-09 20:19 UTC, IrimieBogdan commented on lib/models/fact_collection.rb
> +        next if (fact.type == :core || fact.type == :legacy) && fact.value.nil?
Great suggestion, made the change!

2020-04-10 11:21 UTC, Filipovici-Andrei requested changes

2020-04-10 11:21 UTC, Filipovici-Andrei commented on spec/facter/model/fact_collection_spec.rb
> +        before do
this before block is already defined

2020-04-10 11:21 UTC, Filipovici-Andrei commented on spec/facter/model/fact_collection_spec.rb
> +        before do
this before block is already defined

2020-04-10 11:21 UTC, Filipovici-Andrei commented on spec/facter/model/fact_collection_spec.rb
> +        it 'does not add fact to collection' do
this test repeats, it can be added into a shared_example

2020-04-10 11:21 UTC, Filipovici-Andrei commented on spec/facter/model/fact_collection_spec.rb
> +        before do
this before block is already defined and the user_query can be put in a let block

2020-04-10 14:48 UTC, IrimieBogdan commented on spec/facter/model/fact_collection_spec.rb
> +        it 'does not add fact to collection' do
I would avoid `shared_example`  as it can become confusing very fast

2020-04-10 14:54 UTC, IrimieBogdan commented on spec/facter/model/fact_collection_spec.rb
> +        before do
Moved before block in the upper context.

2020-04-10 14:54 UTC, IrimieBogdan commented on spec/facter/model/fact_collection_spec.rb
> +        before do
Moved before block in the upper context

2020-04-10 14:54 UTC, IrimieBogdan commented on spec/facter/model/fact_collection_spec.rb
> +        before do
Moved before block in the upper context

2020-04-12 16:30 UTC, oanatmaria commented on spec/facter/model/fact_collection_spec.rb
> +        # let(:resolved_fact) { Facter::ResolvedFact.new('os.version', nil, :legacy) }
remove commented line

2020-04-13 07:03 UTC, IrimieBogdan commented on spec/facter/model/fact_collection_spec.rb
> +        # let(:resolved_fact) { Facter::ResolvedFact.new('os.version', nil, :legacy) }
Removed commented line

2020-04-13 07:13 UTC, oanatmaria approved these changes

2020-04-13 07:27 UTC, Filipovici-Andrei approved these changes

2020-04-13 07:27 UTC, merged